'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def Fibonacci_under_n(n):
    previous1 = 1
    previous2 = 2
    current = previous1 + previous2
    list = [1, 2]
    while current <= n:
        list.append(current)
        previous1 = previous2
        previous2 = current
        current = previous1 + previous2
    return list

def check_even(i):
    return i % 2 == 0

sum = 0
for i in Fibonacci_under_n(4000000):
    if check_even(i):
        sum += i

print(sum)
# 4613732
